- .prettierrc.yml
- package.json
> Package.json name change. Add prettier settings

- package.json
- server/db/models/cartedProduct.js
- server/db/models/index.js
- server/db/models/user.js
- server/db/models/user.spec.js
> create user model, cartedProduct model, associations, and login route.

- client/app.js
- client/components/index.js
- client/components/navbar.js
- package-lock.json
- package.json
- public/index.html
- server/db/models/index.js
- server/db/models/user.spec.js
> Bootstrap styles. Test on Navbar

- script/seed.js
- server/api/products.js
> remove unused variable and console logs

- .prettierrc.yml
- client/components/navbar.js
- package.json
Updated navbar. Added authors to package.json.
> Update navbar, add authors in package.json

- client/components/SingleProduct.js
- client/store/products.js
- server/db/models/product.js
add to cart button and saving cart in local storage!!!
> feat: addToCart localStorage

- client/components/Cart.js
- client/components/SingleProduct.js
- client/components/index.js
- client/components/navbar.js
- client/components/signup-form.js
- client/components/user-home.js
- client/routes.js
- client/store/cart.js
- client/store/products.js
- package-lock.json
- package.json
- server/api/cart.js
- server/api/index.js
- server/db/models/order.js
- server/db/models/product.js
- server/db/models/user.js
> Local storage - added cart component

- client/components/user-home.js
- server/api/cart.js
- server/db/models/index.js
- server/db/models/order.js
> feat: Add order class methods. Add routes for cart

- client/components/Cart.js
- client/components/SingleProduct.js
- client/store/index.js
- server/api/cart.js
- server/db/models/order.js
- server/db/models/selectedItem.js
> Feat: updated localstorage and cart component

- server/api/products.js
- server/api/products.spec.js
- server/api/users.spec.js
- server/db/models/order.js
- server/db/models/order.spec.js
> Test: edited Order model and product route tests

- client/components/Cart.js
- client/components/Home.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- public/style.css
> feat: home page for everyone to see

- client/components/AllProducts.js
updating import link to correct file
> bug: fix import link for guestCart

- client/components/SingleProduct.js
- script/seed.js
- script/seedUserProducts.js
> Fix: had some fun seeding more data and adding users

- client/app.js
- client/components/Cart.js
- client/components/Footer.js
- client/components/index.js
- public/style.css
> Feat: add footer component. Style: footer component

- client/components/Cart.js
- client/components/SingleCartItem.js
- client/components/SingleCartItem.spec.js
- script/seedUserProducts.js
> test: SingleCartItem disconnected component

- client/components/AllProducts.js
- client/components/OrderConfirmation.js
- client/components/SingleCartItem.spec.js
- client/components/allProducts.spec.js
- client/store/checkoutCart.js
- package-lock.json
- package.json
- server/api/cart.js
> All product test spec

- client/components/Cart.js
- client/components/SingleCartItem.js
- public/style.css
> Style: cart items. Feat: add button on empty card page.

- client/store/guestCart.spec.js
> test: redux store guestCart state

- client/components/AllProducts.js
- client/components/SingleCartItem.js
- client/components/SingleProduct.js
- public/style.css
Still needs work when wrapping screen
> Style: single cart item

- server/api/admin.js
> fix: dont show pw of users

- package-lock.json
- package.json
- script/seed.js
- script/seedUserProducts.js
> Feat: seeding fake user data with faker

- client/store/cart.js
- server/api/cart.js
- logged in cart only shows items from active order
- shows 'out of stock' alert if user tries to add item that is not in stock
> feat: alerts out of stock

- client/components/SingleProduct.js
- client/store/checkoutCart.js
- client/store/products.js
- public/style.css
- script/seed.js
- script/seedUserProducts.js
- server/api/admin.js
> Style: Update product quantity

- client/components/AllProducts.js
- client/components/NewProductForm.js
- client/components/SingleProduct.js
- client/store/products.js
- public/style.css
- server/api/admin.js
- server/db/models/product.js
> Feat: add new item form updates db and allproducts component

- client/components/NewProductForm.js
- client/store/products.js
> Bug: delete a link on button

- client/components/SingleProduct.js
> Fix: moved divs for guest product

- client/components/SingleProduct.js
- script/seedUserProducts.js
> fix: fixed roles for andrew and anthony

- client/components/AllUsers.js
- client/components/SingleProduct.js
- public/style.css
Added padding for users page and centered admin update product section
> Styles: small CSS touches

- client/store/cart.spec.js
- server/api/index.js
> Fix: test specs bugs

- client/store/cart.spec.js
- public/style.css
- server/api/index.js
> Style : centered title

- .gitignore
> Fix: gitigrone
